### ISSUE TITLE
Сделать импорт стилей компонент динамическим

### ISSUE THREAD

**Issue by Znack** [rustho/TaskFullStackDev#15]
У тебя сейчас 7 компонент, если будешь добавлять 8-ой, то тебе придется ручками еще помимо создания компонента добавлять его импорт в main.styl, что естественно забудешь сделать. Поэтому можно проблему сразу решить красиво, динамически импортируя все стили блоков со всей папки компонент

**Comment by rustho** [comment]
Ну чет меня смущает моё решение, но он вроде правильное (((: 
@import "components/*" ?

**Comment by Znack** [comment]
не, норм, особенно если работает :)
