### ISSUE TITLE
Убрать все лишние стили. 

### ISSUE THREAD

**Issue by Znack** [rustho/TaskFullStackDev#16]
Просто пройдись по проекту и проверяй все стили у всех компонент. Все лишнее вырубить к чертям. Например, флексы у колонок почти наверняка не нужны.

**Comment by Znack** [comment]
По этой таске детально специально говорить не будем, где косяки, просто если найдем опять, снова скажем, что "ишью не закрыт, ищи сам" :)

**Comment by Znack** [comment]
У тебя по проекту довольно много находится правил, которые можно спокойно выключить и все будет на месте :) Это нормально для проекта, который уже переделывался несколько раз и для тебя это отличный пример, что надо всегда за собой подчищать. Легаси — довольно болезненная штука в проекте, так что сейчас тебе обязательно надо на примере показать, что ты его можешь качественно вычистить

**Comment by rustho** [comment]
Подчистил вроде бы
