### ISSUE TITLE
Pixel Perfect страдает

### ISSUE THREAD

**Issue by Znack** [rustho/TaskFullStackDev#20]
![image](https://user-images.githubusercontent.com/2928964/30843109-4582d7d2-a2b1-11e7-8e68-4053df7463a3.png)

Потом как поправишь, напиши при какой ширине экрана сверял и при каком масштабе макета в расширении PixelPerfect у хрома

**Comment by rustho** [comment]
Страннота на самом деле, 0.45 - масштаб, ширина 1152
