### ISSUE TITLE
Убрать лишнюю img, раз сверстал круг по цсс

### ISSUE THREAD

**Issue by Znack** [rustho/TaskFullStackDev#21]
`<img src="">` у тебя в иотге в сборке лишний 

Хром это явно подсвечивает битой картинкой:

![image](https://user-images.githubusercontent.com/2928964/30843182-a8419ca0-a2b1-11e7-8f8a-3c037dc27138.png)

**Comment by rustho** [comment]
убрал, оставлял так как, сюда ж фотку надо по сути вставлять
