### ISSUE TITLE
Стили компонента должны быть рядом с компонентом

### ISSUE THREAD

**Issue by Znack** [rustho/TaskFullStackDev#22]
Еще раз: стили каждого компонента только внутри папки этого компонента, и нигде больше по системе. Это очень важно, хотя и сложно на практике соблюдать. Хороший пример твоего косяка: компонент elemOfList

И кстати у него сделай имя паг файла главного и имя папки компонента одинаковым. И в целом всегда именуй главный миксин так же как название папки с компонентом

**Comment by rustho** [comment]
сделал
