### ISSUE TITLE
Переписать стили

### ISSUE THREAD

**Issue by Zarwlar** [rustho/TaskFullStackDev#3]
Сейчас вёрстка не по БЭМу

**Comment by rustho** [comment]
Оу, а что именно не по бэму? В стандартах именно так описано делать

**Comment by Zarwlar** [comment]
Скинь ссылку на это сообщение плиз

**Comment by rustho** [comment]
https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_78tp6/
Топик стандартов,CSS опасная сила, вообще по бэму верстка должна лежать в мастере можешь там глянуть

**Comment by Zarwlar** [comment]
Хорошо, тогда по rscss:
1. Prefer to use the > child selector whenever possible. This prevents bleeding through nested components, and performs better than descendant selectors.
2. Use classnames whenever possible. Tag selectors are fine, but they may come at a small performance penalty and may not be as descriptive.

**Comment by rustho** [comment]
Доделал (: Теперь точно всё по rscss (:
