### ISSUE TITLE
Тяжелочитаемый код

### ISSUE THREAD

**Issue by Zarwlar** [rustho/TaskFullStackDev#37]
Здесь слишком много инструкций в одной строчке:
`class=(val++<number)? "progress-line__item_type_checked": "progress-line__item_type_unchecked",`
А здесь (строчку кода, которая находится выше это тоже касается) нужно добавить пробелы, чтобы точка читалась лучше. + Зачем здесь скобки после знака `=`?
`class=(type)? "progress-line__item_type_"+type : ""`

**Comment by rustho** [comment]
```
class= (val<number) ? "progress-line__item_type_checked": "progress-line__item_type_unchecked",
class= type ? "progress-line__item_type_"+type : "",
data-at=val++
```
как-то костыльно сделал, по-другому вроде нельзя итерацию сделать, зацикливается и умирает всё

**Comment by Geksanit** [comment]
по-другому сделать всегда можно

**Comment by Geksanit** [comment]
1. три тернарника можно заменить одним.
2. где сам блок `.progress-line` ?
3. если вдруг придется изменить количество или порядок аргументов миксина, как сейчас  это будет не удобно. Можно по другому получать аргументы. Лучше если сам догадаешься.

**Comment by rustho** [comment]
1 - хз насчет одного, мне же и тип надо передавать и вычислять закрашенный или нет
2 - исправил
3 - тоже исправил, чет затупил (:

**Comment by Geksanit** [comment]
2 - модификатор достаточно вычислить один раз
`const modifier = options.type || '';`
а потом конкатенировать.

**Comment by Geksanit** [comment]
`div.progress-line` - лучше без дива `.progress-line`, он всегда по умолчанию.

**Comment by Geksanit** [comment]
_checked - это булев модификатор ? если да, то альтернативное состояние обозначает его отсутствие, а не _unchecked

**Comment by rustho** [comment]
1 - чет не до конца понял насчет "модификатор достаточно вычислить один раз", т.е. в самом начале в любом случае вычисляем какой-то модификатор, который мы добавим к, допустим, div, а после уже его просто class=modificator? так вроде еще более запутанно происходит...
2 - ну да, тогда по сути от всех дивов нужно избавиться вообще... а в целом div - сразу понятно о чем речь
3 - да, и вправду, так намного проще выглядит

**Comment by Geksanit** [comment]
Как вариант можно добавлять модификатор только самому блоку (обычно так и делают), но тогда стили должны быть написаны по-другому.

**Comment by rustho** [comment]
Хм... ну каскадом же нельзя стили мутить, тогда смысл добавлять модификатор только самому блоку?

**Comment by Geksanit** [comment]
Каскадом можно, но вложенностью не более 3.

**Comment by rustho** [comment]
Ну вот так тогда

**Comment by Geksanit** [comment]
Вот теперь стало лучше.
используй ссылку на родителя http://stylus-lang.com/docs/selectors.html#partial-reference

**Comment by rustho** [comment]
ооооо, точняк... я пытался вчера замутить это, но не так немного

**Comment by rustho** [comment]
Окей, а вот вопрос, как лучше оформлять? 
`
.progress-line
  &__header 
    font-size:1.54rem;
    ^[0]_type_software &
      color: black;
`
или 

`
.progress-line
  &__header 
    font-size:1.54rem;
  &_type_software &
    &__header
       color: black;
`

**Comment by Geksanit** [comment]
первый вариант лучше

**Comment by rustho** [comment]
готово
