### ISSUE TITLE
длинный текст ломает вёрстку

### ISSUE THREAD

**Issue by Geksanit** [rustho/TaskFullStackDev#38]
Вёрстка не должна ломаться при любых вводных данных.
![2018-03-21 16-15-53](https://user-images.githubusercontent.com/31949379/37701935-75fc17b4-2d23-11e8-8965-2b0b543b6b8a.png)

**Comment by rustho** [comment]
Насчет названия блоков, их тоже верстать так чтобы не ломалось? (название блоков же вроде неизменное, иначе зачем)
