### ISSUE TITLE
мелкие ошибки

### ISSUE THREAD

**Issue by Geksanit** [rustho/TaskFullStackDev#39]
1. в контактах  у ссылки на вебсайт должен быть дополнительный атрибут, смотри в стандартах.
2. ошибка в консоли из-за фавиконки. её нет или ссылка неправильная.

**Comment by rustho** [comment]
исправил

**Comment by Geksanit** [comment]
фавиконки всё равно нету. сделай как [тут](https://medium.com/tech-angels-publications/bundle-your-favicons-with-webpack-b69d834b2f53)

**Comment by rustho** [comment]
Так, чет я хз, иконка у меня появилась нормально, в вебпакдевсервере она не работает даже тем способом что ты мне кинул
